# /member/member/count中第一个member是模块名，第二个member是数据表名，后跟操作名
GET http://localhost:8000/member/member/count
Accept: application/json
###
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=

###
POST http://localhost:8000/member/member/sendCode
Content-Type: application/json

{
  "mobile": ""
}

###
#登录测试，并使用HTTPClient保存JWT为全局变量，供其他测试使用
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "18000000000",
  "code": "8888"
}

> {%
client.log(JSON.stringify(response.body));
client.log(JSON.stringify(response.body.content.token));
client.global.set("test_token", response.body.content.token);
%}