# /member/member/count中第一个member是模块名，第二个member是数据表名，后跟操作名
GET http://localhost:8000/member/member/count
Accept: application/json
###
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=

###
POST http://localhost:8000/member/member/sendCode
Content-Type: application/json

{
  "mobile": ""
}

###
POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded

mobile= &code=